language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t hoier14/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true hoier14/docker-react npm run test